= Spring REST Service OAuth

The RESTful web-service that allows registering and connecting users.

It's built with Spring Boot and Spring Security OAuth.
It uses http://oauthlib.readthedocs.org/en/latest/oauth2/grants/password.html[Resource Owner Password Credentials Grant]
to protect its endpoints.

1. The client application uses basic authentication to access all endpoints in the webapp
2. The user gives the client app the user's login and password.
3. The client exchanges the user's credentials for a token that gives it the access to the user's resources.

= Running and testing

1. Start application:
+
```
./gradlew clean build bootRun
```

2. Test user endpoints:
a. Register userA:
+
```
curl -X POST -H "Content-Type: application/json" http://localhost:8080/register -d \
'{"username":"userA","password":"secret"}'
```
+
Expected response:
+
```
{"userId":"userA","username":"userA"}
```

b. Register userB:
+
```
curl -X POST -H "Content-Type: application/json" http://localhost:8080/register -d \
'{"username":"userB","password":"secret"}'
```
+
Expected response:
+
```
{"userId":"userB","username":"userB"}
```

c. Obtain userA's token:
+
```
curl -X POST -vu clientapp:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d \
"password=secret&username=userA&scope=read%20write&grant_type=password&client_secret=123456&client_id=clientapp"
```
+
Expected response:
+
```
{"access_token":"<your-token>","token_type":"bearer","refresh_token":"6783d235-2e66-4bf9-a79c-87c8d401e000","expires_in":43199,"scope":"read write"}
```

d. As userA, search for all users whose names contain string "user"
+
```
curl -H "Accept: application/json" -H "Authorization: Bearer <your-token>" http://localhost:8080/users?nameContains=user
```
+
Expected response:
+
```
[{"userId":"userB","username":"userB"},
 {"userId":"userA","username":"userA"}]
```

e. As userA, connect with userB:
+
```
curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer <your-token>" http://localhost:8080/users/userA/connections -d '{"userId": "userB"}'
```
+
Expected response:
+
```
{"userId":"userA","username":"userA","connections":["userB"]}
```

3. Test admin endpoints:
a. Obtain admin token (the application creates a default admin account):
+
```
curl -X POST -vu clientapp:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d \
"password=admin&username=admin&scope=read%20write&grant_type=password&client_secret=123456&client_id=clientapp"
```
+
Expected response:
+
```
{"access_token":"<your-token>","token_type":"bearer","refresh_token":"247e1719-b053-4129-bb22-27124c4fc035","expires_in":42639,"scope":"read write"}
```

b. List all the users with their connections:
+
```
curl -H "Accept: application/json" -H "Authorization: Bearer <your-token>" http://localhost:8080/admin/users
```
+
Expected response:
+
```
[{"userId":"userA","username":"userA","connections":["userB"]},
 {"userId":"userB","username":"userB","connections":["userA"]},
 {"userId":"admin","username":"admin","connections":[]}]
```

= API

== Create user

Role: none
```
POST /users/

{
   "username": "abc",
   "password": "1234"
}
```
response:
```
201 CREATED

{
   "userId": "abc",
   "username": "abc"
}
```
== Get user details

Role: USER
```
GET /users/{userId}
```
response:
```
200 OK

{
   "userId": "abc",
   "username": "abc"
}
```
== Add a connection

Role: USER
```
POST /users/{userId}/connections

{
   "userId": "xyz"
}
```
response:
```
201 CREATED

{
   "userId": "abc",
   "username": "abc",
   "connections": [
      "xyz"
   ]
}
```
== Get user connections

Role: ADMIN
```
GET /admin/users/{userId}
```
response:
```
200 OK

{
   "userId": "abc",
   "username": "abc"
   "connections": [
      "xyz",
      "pqr"
   ]
}
```
= Original documentation

image::https://travis-ci.org/royclarkson/spring-rest-service-oauth.svg[Build Status, link=https://travis-ci.org/royclarkson/spring-rest-service-oauth/]

This is a simple REST service that provides a single RESTful endpoint protected by OAuth 2. The REST service is based on the https://spring.io/guides/gs/rest-service/[Building a RESTful Web Service] getting started guide. This project incorporates the new Java-based configuration support, now available in Spring Security OAuth 2.0. Please log any issues or feature requests to the https://github.com/spring-projects/spring-security-oauth/issues[Spring Security OAuth project].


== Spring Projects

The following Spring projects are used in this sample app:

* http://projects.spring.io/spring-boot/[Spring Boot]
* http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html[Spring MVC]
* http://projects.spring.io/spring-security/[Spring Security]
* http://projects.spring.io/spring-security-oauth/[Spring Security OAuth]
* http://projects.spring.io/spring-data-jpa/[Spring Data JPA]


== Build and Run

Use Gradle:

```sh
./gradlew clean build bootRun
```

Or Maven:

```sh
mvn clean package spring-boot:run
```

== Usage

Test the `greeting` endpoint:

```sh
curl http://localhost:8080/greeting
```

You receive the following JSON response, which indicates you are not authorized to access the resource:

```json
{
  "error": "unauthorized",
  "error_description": "An Authentication object was not found in the SecurityContext"
}
```

In order to access the protected resource, you must first request an access token via the OAuth handshake. Request OAuth authorization:

```sh
curl -X POST -vu clientapp:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d "password=spring&username=roy&grant_type=password&scope=read%20write&client_secret=123456&client_id=clientapp"
```

A successful authorization results in the following JSON response:

```json
{
  "access_token": "ff16372e-38a7-4e29-88c2-1fb92897f558",
  "token_type": "bearer",
  "refresh_token": "f554d386-0b0a-461b-bdb2-292831cecd57",
  "expires_in": 43199,
  "scope": "read write"
}
```

Use the `access_token` returned in the previous request to make the authorized request to the protected endpoint:

```sh
curl http://localhost:8080/greeting -H "Authorization: Bearer ff16372e-38a7-4e29-88c2-1fb92897f558"
```

If the request is successful, you will see the following JSON response:

```json
{
  "id": 1,
  "content": "Hello, Roy!"
}
```

After the specified time period, the `access_token` will expire. Use the `refresh_token` that was returned in the original OAuth authorization to retrieve a new `access_token`:

```sh
curl -X POST -vu clientapp:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d "grant_type=refresh_token&refresh_token=f554d386-0b0a-461b-bdb2-292831cecd57&client_secret=123456&client_id=clientapp"
```


== SSL

To configure the project to run on HTTPS as shown in https://spring.io/guides/tutorials/bookmarks/[Building REST services with Spring], enable the `https` profile. You can do this by uncommenting the appropriate line in the application.properties file of this project. This will change the server port to `8443`. Modify the previous requests as in the following command.

```sh
curl -X POST -k -vu clientapp:123456 https://localhost:8443/oauth/token -H "Accept: application/json" -d "password=spring&username=roy&grant_type=password&scope=read%20write&client_secret=123456&client_id=clientapp"
```

The `-k` parameter is necessary to allow connections to SSL sites without valid certificates or the self signed certificate which is created for this project.


== Cloud Foundry Demo

The service is deployed to Pivotal Cloud Foundry and available for testing. Modify the previous commands to point to the following URL:

```sh
curl http://rclarkson-restoauth.cfapps.io/greeting
```
